# Generated by Django 4.2.3 on 2023-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=32)),
                ('registered_at', models.DateField()),
                ('last_login', models.TimeField()),
            ],
        ),
    ]
