# Generated by Django 4.2.3 on 2023-08-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
